min-version: v0.11.0
formatter: default
rules:
  - header-min-length
  - header-max-length
  - body-max-line-length
  - footer-max-line-length
  - type-enum
severity:
  default: error
settings:
  body-max-line-length:
    argument: 100
  footer-max-line-length:
    argument: 100
  header-max-length:
    argument: 72
  header-min-length:
    argument: 10
  type-enum:
    argument:
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
